"""Add squads and squad_members

Revision ID: 3078b6cdc1ee
Revises: 504ce2b8693a
Create Date: 2026-08-08 10:00:42.253133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3078b6cdc1ee'
down_revision: Union[str, None] = '504ce2b8693a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organiser_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_squads_organiser_id', 'squads', ['organiser_id'], unique=False)
    op.create_table('squad_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('invite_email', sa.String(length=255), nullable=True),
    sa.Column('invite_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'invite_email', name='uq_squad_member_email'),
    sa.UniqueConstraint('squad_id', 'user_id', name='uq_squad_member_user')
    )
    op.create_index('ix_squad_members_invite_email', 'squad_members', ['invite_email'], unique=False)
    op.create_index('ix_squad_members_squad_id', 'squad_members', ['squad_id'], unique=False)
    op.create_index('ix_squad_members_user_id', 'squad_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_squad_members_user_id', table_name='squad_members')
    op.drop_index('ix_squad_members_squad_id', table_name='squad_members')
    op.drop_index('ix_squad_members_invite_email', table_name='squad_members')
    op.drop_table('squad_members')
    op.drop_index('ix_squads_organiser_id', table_name='squads')
    op.drop_table('squads')
    # ### end Alembic commands ###
