"""Add marketplace visibility to games

Revision ID: 340162702137
Revises: 9bf72585a643
Create Date: 2026-08-08 12:06:14.575370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340162702137'
down_revision: Union[str, None] = '9bf72585a643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required, not cosmetic: adding a NOT NULL column to a
    # table that already has rows fails without one. It also backfills every
    # existing game to 'public', preserving the behaviour they had before
    # visibility existed — they were all publicly listed.
    op.add_column(
        'games',
        sa.Column(
            'visibility',
            sa.String(length=20),
            nullable=False,
            server_default='public',
        ),
    )
    op.add_column('games', sa.Column('marketplace_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('marketplace_notified_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'marketplace_notified_at')
    op.drop_column('games', 'marketplace_opened_at')
    op.drop_column('games', 'visibility')
    # ### end Alembic commands ###
