services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: btf
      POSTGRES_PASSWORD: btf_local
      POSTGRES_DB: bethefifth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
